[build]
buildCommand = "cd Backend/SecureCarbonX/ai-service && pip install -r requirements.txt"

[deploy]
startCommand = "cd Backend/SecureCarbonX/ai-service && uvicorn app:app --host 0.0.0.0 --port $PORT"
